# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

RUN npm install --ignore-scripts

COPY . .

# Ensure tsc is executable
RUN chmod +x ./node_modules/.bin/tsc

RUN npm run build

CMD ["node", "dist/index.js"]
